version: '2'
services:
  blog:
    container_name: blog
    build: .
    ports: 
      - 80:4000   # 映射端口， 80端口请自行修改为未被占用的端口
    volumes:
      - .:/usr/src/app:rw
    environment:
      TZ: Asia/Shanghai